env:
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Test"
  container:
    image: anggit86/ubuntu:22.04
    cpu: 4
    memory: 16G

  Test_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/NFS-Project/cirrus-ci-skrip/master/rom/checks.sh)"
